@startuml
title Load Users
participant actor
participant DataManager as DM
participant ArrayList as users
' from within DataManager
participant File 
' new("usersfile")
participant FileReader as fReader
' FileReader(file)
participant BufferedReader as reader
'new(fReader)
'reader.line()
participant User

actor -> DM: loadUsers()
activate DM
DM -> users: new()
DM -> File: new("usersfile")
DM -> fReader: FileReader(file)
DM -> reader: new(fReader)

loop while (next line)
    DM -> reader: readLine()
    DM -> User: fromCSV(line)
    DM -> DM: loadExpensesForUser(user)
    DM -> DM: loadBudgetsForUser(user)
    DM -> ArrayList: add(user)
    end
DM --> actor: users
deactivate DM
@enduml