@startuml
' -> mainMenu: handleViewSummary()
' loop over Category.values()
' -> currentUser (User):    getBudget(category).limit()
' -> expenseService:    getTotalByCategory(currentUser, category)
' -> budgetService:     getRemainingBudget(currentUser, category)
actor user
participant "mainMenu: MainMenu" as mainMenu
participant "currUser: User" as currUser
participant "budgetService: BudgetService" as budgetService
participant "expenseService: ExpenseService" as expenseService
'participant "loginService: LoginService" as loginService

user -> mainMenu: handleViewSummary()
'mainMenu -> Category: values()
loop each category of expense as c
    mainMenu -> currUser: getBudget(c)
    mainMenu -> budgetService: getRemainingBudget(currUser, c)
    mainMenu -> expenseService: getTotalByCategory(currUser, c)
end
mainMenu --> actor: result
@enduml