@startuml
title Delete Transaction
actor user
participant "mainMenu: MainMenu" as mainMenu
participant "loginService: LoginService" as loginService
participant "expenseService: ExpenseService" as expenseService
participant "currUser: User" as currUser
participant "allExpenses: List<Expense>" as allExpenses

activate mainMenu
    user -> mainMenu: handleLogin()
    
    activate loginService
        mainMenu -> loginService: login(username, password)
        loginService --> mainMenu: currUser: User
    deactivate loginService
    mainMenu --> user: logged-in confirmation

    
    mainMenu -> mainMenu: showUserMenu()
    'showUserMenu()
    activate mainMenu
        ' User chooses 3. Delete a transaction
        mainMenu --> user: shows options
        
            user -> mainMenu: handleDeleteTransaction()
            activate mainMenu

                ' Show all current transactions
                mainMenu -> mainMenu: printAllTransactions()
                    activate mainMenu 
                    mainMenu --> user: results
                    deactivate mainMenu 
                ' end of menu: printAllTransactions()

                mainMenu -> mainMenu: selectExpense()
                    activate mainMenu
                    
                    mainMenu -> expenseService: findExpense(currentUser, name, amount, date)
                    activate expenseService
                    expenseService --> mainMenu: expense: Expense
                    deactivate expenseService

                    mainMenu --> mainMenu: expense: Expense
                    deactivate mainMenu
                ' end of selectExpense

                mainMenu -> expenseService: deleteExpense(currUser, expense)
                activate expenseService
                    expenseService -> currUser: getExpenses()
                    currUser --> expenseService: allExpenses: List<Expense>
                    expenseService -> allExpenses: remove(expense)
                deactivate expenseService

                mainMenu --> user: "Succesfull deletion of transaction

            'deactivate handleDeleteTransaction()
            deactivate mainMenu 

    'deactivate showUserMenu()
    deactivate mainMenu

'mainMenu: show()
@enduml