@startuml
' -> mainMenu: handleViewSummary()
' loop over Category.values()
' -> currentUser (User):    getBudget(category).limit()
' -> expenseService:    getTotalByCategory(currentUser, category)
' -> budgetService:     getRemainingBudget(currentUser, category)
actor user
participant "mainMenu: MainMenu" as mainMenu
participant "currUser: User" as currUser
participant "budget: Budget" as budget
participant "budgetService: BudgetService" as budgetService
participant "expenseService: ExpenseService" as expenseService
'participant "loginService: LoginService" as loginService

user -> mainMenu: handleViewSummary()
'mainMenu -> Category: values()
loop each category of expense as c
    activate currUser
        mainMenu -> currUser: getBudget(c)
        currUser --> mainMenu: budget: Budget
    deactivate currUser

    activate budget
        mainMenu -> budget: getLimit()
        budget --> mainMenu: limit: double
    deactivate budget

    activate budgetService
    mainMenu -> budgetService: getRemainingBudget(currUser, c)
    budgetService --> mainMenu: remaining: double
    deactivate budgetService

    activate expenseService
    mainMenu -> expenseService: getTotalByCategory(currUser, c)
    expenseService --> mainMenu: total: double
    deactivate expenseService

    ' result for each category 
    mainMenu --> user: results for category c
end

mainMenu --> user: grand total 
@enduml