@startuml
title 2. Edit Transaction
actor user
participant "mainMenu:\nMainMenu" as mainMenu
participant "loginService:\nLoginService" as loginService

participant "expenseService:\nExpenseService" as expenseService
participant "currUser:\nUser" as currUser
participant "expenseList:\nList" as expenseList
participant "selectedExpense:\nExpense" as selectedExpense

' FIRST login
activate mainMenu
user -> mainMenu: handleLogin()
    activate loginService
        mainMenu -> loginService: login(username, password)
        loginService --> mainMenu: currUser: User
    deactivate loginService
    mainMenu --> user: "You are logged in"
deactivate mainMenu
' now logged in, proceed'

'showUserMenu()
user -> mainMenu: showUserMenu()
activate mainMenu
    ' User chooses 2. Edit a transaction
    mainMenu --> user: shows options
        
        user -> mainMenu: handleEditTransaction()
        activate mainMenu

            ' Show all current transactions
            mainMenu -> mainMenu: printAllTransactions()
            activate mainMenu 

                activate expenseService
                mainMenu -> expenseService: sortExpenses(currUser, date)
                    activate currUser
                        expenseService -> currUser: getExpenses()
                        currUser --> expenseService: List<Expense>
                    deactivate currUser
                    expenseService -> expenseList: sort()

                    expenseService --> mainMenu: expenseList: List<Expense>
                deactivate expenseService
                
                'show all expenses
                loop for expense in\nexpenses as e
                    mainMenu --> user: results
                end
            deactivate mainMenu 
            ' end of menu: printAllTransactions()

            ' Enter information for a specific transaction, selectExpense()
            user -> mainMenu: selectExpense()
            activate mainMenu 
                ' expenseService finds an expense based on on info
                activate expenseService
                    mainMenu -> expenseService: findExpense(\n\tcurrentUser, name,\n\tamount, date)
                    expenseService --> mainMenu: expense: Expense
                deactivate expenseService
                mainMenu --> mainMenu: selectedExpense: Expense
            deactivate mainMenu 
            ' end of menu: selectExpense()

            ' expenseService edits
            mainMenu -> expenseService: editExpense(\n\tselectedExpense, newName,\n\tnewAmount, newCategory, newDate)
            activate expenseService
                expenseService -> selectedExpense: setName(newName) 
                expenseService -> selectedExpense: setAmount(newAmount)
                expenseService -> selectedExpense: setCategory(newCategory)  
                expenseService -> selectedExpense: setDate(newDate) 
            deactivate expenseService

            mainMenu --> user: "Edit successfull"
        'deactivate handleEditTransaction()
        deactivate mainMenu 

'deactivate showUserMenu()
'deactivate mainMenu

'mainMenu: show()
@enduml