@startuml
title 1. Add Expense
actor user
participant "mainMenu:\nMainMenu" as mainMenu
participant "loginService:\nLoginService" as loginService
participant "budgetService:\nBudgetService" as budgetService

' FIRST login
activate mainMenu
user -> mainMenu: handleLogin()
    activate loginService
        mainMenu -> loginService: login(username, password)
        loginService --> mainMenu: currUser: User
    deactivate loginService
    mainMenu --> user: "You are logged in"
deactivate mainMenu
' now logged in, proceed'

'showUserMenu()
user -> mainMenu: showUserMenu()
activate mainMenu
    ' User chooses 1. Add Expense
    mainMenu --> user: shows options
        
    'handleAddExpense
    user -> mainMenu: handleAddExpense()
    activate mainMenu
        ' Choose category of expense
        'mainMenu --> user: choose category in which to add expense

        ' System checks budget limit
        activate budgetService
            mainMenu -> budgetService: checkBudget(currUser, category, amount)
            budgetService --> mainMenu: result: boolean
        deactivate budgetService

        'Adds expense
        create Expense
        mainMenu ->  Expense: new(name, amount, category, date)
        
        mainMenu -> "expenseService:\nExpenseService" as expenseService: addExpense(currUser, exp: Expense)
        activate expenseService
        deactivate expenseService

        mainMenu --> user: "Expense added"
    'deactivate handleAddExpense()
    deactivate mainMenu 

'deactivate showUserMenu()
'deactivate mainMenu

'mainMenu: show()
@enduml